[TF] Set up TensorFlow high-level API repository.
Add TensorFlow high-level API repository.
Currently, the repository lives at https://github.com/rxwei/DeepLearning.

Clone sources from repository into the TensorFlow module.

The high-level API repository version is pinned in
`utils/update_checkout/update-checkout-config.json`.

diff --git a/utils/build-script-impl b/utils/build-script-impl
--- a/utils/build-script-impl
+++ b/utils/build-script-impl
@@ -1202,6 +1202,7 @@ PLAYGROUNDSUPPORT_SOURCE_DIR="${WORKSPACE}/swift-xcode-playground-support"
 # SWIFT_ENABLE_TENSORFLOW
 TENSORFLOW_SOURCE_DIR="${WORKSPACE}/tensorflow"
 TENSORFLOW_SWIFT_BINDINGS_DIR="${WORKSPACE}/tensorflow-swift-bindings"
+TENSORFLOW_SWIFT_APIS_DIR="${WORKSPACE}/tensorflow-swift-apis"
 
 if [[ ! "${SKIP_BUILD_PLAYGROUNDSUPPORT}" && ! -d ${PLAYGROUNDSUPPORT_SOURCE_DIR} ]]; then
     echo "Couldn't find PlaygroundSupport source directory."
@@ -1215,6 +1216,10 @@ if [[ "${ENABLE_TENSORFLOW}" ]]; then
     fi
     if [[ "${TENSORFLOW_SWIFT_BINDINGS}" && ! -f "${TENSORFLOW_SWIFT_BINDINGS}" ]]; then
         echo "Invalid TensorFlow Swift bindings file specified."
+        exit 1
+    fi
+    if [[ "${TENSORFLOW_SWIFT_APIS}" && ! -d "${TENSORFLOW_SWIFT_APIS}" ]]; then
+        echo "Invalid TensorFlow high level APIs repository specified."
         exit 1
     fi
 fi
@@ -2424,6 +2429,16 @@ for host in "${ALL_HOSTS[@]}"; do
                         cmake_options=(
                             "${cmake_options[@]}"
                             -DTENSORFLOW_SWIFT_BINDINGS:PATH="${TENSORFLOW_SWIFT_BINDINGS}"
+                        )
+                    fi
+                    # Handle TensorFlow high-level APIs repository.
+                    if [[ ! "${TENSORFLOW_SWIFT_APIS}" && -d "${TENSORFLOW_SWIFT_APIS}" ]] ; then
+                        TENSORFLOW_SWIFT_APIS="${TENSORFLOW_SWIFT_APIS_DIR}"
+                    fi
+                    if [[ "${TENSORFLOW_SWIFT_APIS}" ]] ; then
+                        cmake_options=(
+                            "${cmake_options[@]}"
+                            -DTENSORFLOW_SWIFT_APIS:PATH="${TENSORFLOW_SWIFT_APIS}"
                         )
                     fi
                 fi
